In [2]:
import numpy as np

Ejercicio Numpy-01
Crea un array 3x4 con valores enteros aleatorios entre 10 y 50. Luego, calcula la suma, la media, y el valor máximo de todo el array.

In [6]:

# Crear un array 3x4 con valores enteros aleatorios entre 10 y 50

array_aleatorio = np.random.randint(10, 51, size=(3, 4))

# Calcular las estadísticas solicitadas

suma_total = np.sum(array_aleatorio)
media_total = np.mean(array_aleatorio)
maximo_total = np.max(array_aleatorio)

# Mostrar resultados
print("Array generado:")
print(array_aleatorio)
print("\nResultados:")
print(f"Suma total: {suma_total}")
print(f"Media total: {media_total:.2f}")  # Formateado a 2 decimales
print(f"Valor máximo: {maximo_total}")

Array generado:
[[26 33 35 13]
 [10 50 46 48]
 [27 12 23 12]]

Resultados:
Suma total: 335
Media total: 27.92
Valor máximo: 50


Ejercicio Numpy-02
Crea una matriz identidad 5x5 y cambia la diagonal principal a un valor de 7.

In [ ]:
# Crear una matriz identidad 5x5
# np.eye(N) crea una matriz identidad de NxN (en este caso 5x5)
# Por defecto, tiene 1s en la diagonal principal y 0s en las demás posiciones

matriz_identidad = np.eye(5)

# Modificar la diagonal principal a 7
# np.fill_diagonal() es una función específica para modificar los valores de la diagonal principal
# Recibe como parámetros la matriz y el valor a asignar (7 en este caso)

np.fill_diagonal(matriz_identidad, 7)

print("Matriz resultante:")
print(matriz_identidad)

Matriz resultante:
[[7. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0.]
 [0. 0. 7. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 7.]]


In [5]:
# Utilizando indices.

# Crear matriz identidad

matriz = np.eye(5)

# Modificar diagonal usando índices

filas, columnas = matriz.shape
for i in range(filas):
    matriz[i, i] = 7

matriz

array([[7., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0.],
       [0., 0., 7., 0., 0.],
       [0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 7.]])

Ejercicio Numpy-03
Dado el array a = np.arange(20), crea un nuevo array con los valores pares mayores que 5 usando boolean masking.

In [ ]:
a = np.arange(20)
mask = (a % 2 == 0) & (a > 5)
resultado = a[mask]

print("Array original:", a)
print("Array filtrado:", resultado)

# a % 2 == 0: Identifica valores pares (divisibles entre 2)
# a > 5: Identifica valores mayores que 5
# &: Combina ambas condiciones (AND lógico)

Array original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Array filtrado: [ 6  8 10 12 14 16 18]


Ejercicio Numpy-04
Dado el array bidimensional siguiente:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Reemplaza todas las entradas de la segunda fila por 0 y luego aplana el array a una dimensión.

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = a.copy()
b[1] = 0
print(b)
b_plano = b.flatten()
b_plano


[[1 2 3]
 [0 0 0]
 [7 8 9]]


array([1, 2, 3, 0, 0, 0, 7, 8, 9])

Ejercicio Numpy-05
Crea dos arrays 1D a y b con valores [1, 2, 3] y [4, 5, 6]. Realiza el producto cruzado, producto escalar y producto externo.

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
cruzado = np.cross(a, b)
escalar = np.dot(a, b)
externo = np.outer(a, b)
print("Array a:", a)
print("Array b:", b)
print("\nProducto cruzado (a x b):", cruzado)
print("Producto escalar (a · b):", escalar)
print("\nProducto externo (a x b):")
print(externo)

Array a: [1 2 3]
Array b: [4 5 6]

Producto cruzado (a x b): [-3  6 -3]
Producto escalar (a · b): 32

Producto externo (a x b):
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


Ejercicio Numpy-06
Crea un array de 10 elementos que vayan de 0 a 100 de forma equiespaciada, redondea cada elemento a su entero más cercano, y luego limita sus valores para que estén entre 20 y 80.

In [ ]:
array = np.linspace(0, 100, 10)
print(array)
array_redondeado = np.round(array).astype(int)
print(array_redondeado)
array_limitado = np.clip(array_redondeado, 20, 80)
print(array_limitado)

# resultado = np.clip(np.round(np.linspace(0, 100, 10)).astype(int), 20, 80)
# print(resultado)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[  0  11  22  33  44  56  67  78  89 100]
[20 20 22 33 44 56 67 78 80 80]


Ejercicio Numpy-07
Crea una matriz aleatoria 4x4 con valores entre 0 y 1. Multiplica la matriz por sí misma (producto matricial) y calcula la traza del resultado.

In [31]:
traza = np.trace(np.dot(matriz := np.random.rand(4,4), matriz))
traza              


np.float64(5.32163598328548)

Ejercicio Numpy-08
Dado el array a = np.array([10, 20, 30, 40, 50]), crea una máscara booleana para seleccionar los elementos que no estén en la lista [20, 40].

In [33]:
a = np.array([10, 20, 30, 40, 50])
mask = ~np.isin(a, [20, 40]) 
# El operador ~ (NOT) invierte la máscara
resultado = a[mask]
resultado

array([10, 30, 50])

Ejercicio Numpy-09
Crea un array 2x3 lleno de 5s, otro 3x2 lleno de 10s, y concaténalos verticalmente tras hacer el reshape adecuado para que la concatenación sea posible.

In [35]:
arr_5s = np.full((2, 3), 5)
arr_10s = np.full((3, 2), 10)

# Mismo numero de columnas
arr_5s_reshaped = arr_5s.reshape(6, 1)
arr_10s_reshaped = arr_10s.reshape(6, 1)

resultado = np.concatenate((arr_5s_reshaped, arr_10s_reshaped), axis=0)

# print(arr_5s_reshaped)
# print(arr_10s_reshaped)
# print(resultado)

print("Array de 5s (2x3):")
print(arr_5s)
print("\nArray de 10s (3x2):")
print(arr_10s)
print("\nArray de 5s redimensionado (6x1):")
print(arr_5s_reshaped)
print("\nArray de 10s redimensionado (6x1):")
print(arr_10s_reshaped)
print("\nConcatenación vertical (12x1):")
print(resultado)


Array de 5s (2x3):
[[5 5 5]
 [5 5 5]]

Array de 10s (3x2):
[[10 10]
 [10 10]
 [10 10]]

Array de 5s redimensionado (6x1):
[[5]
 [5]
 [5]
 [5]
 [5]
 [5]]

Array de 10s redimensionado (6x1):
[[10]
 [10]
 [10]
 [10]
 [10]
 [10]]

Concatenación vertical (12x1):
[[ 5]
 [ 5]
 [ 5]
 [ 5]
 [ 5]
 [ 5]
 [10]
 [10]
 [10]
 [10]
 [10]
 [10]]


In [36]:
arr_5s = np.full((2, 3), 5).reshape(-1, 1)  # -1 significa "calcula automáticamente"
arr_10s = np.full((3, 2), 10).reshape(-1, 1)

resultado = np.vstack((arr_5s, arr_10s))

print(resultado)

[[ 5]
 [ 5]
 [ 5]
 [ 5]
 [ 5]
 [ 5]
 [10]
 [10]
 [10]
 [10]
 [10]
 [10]]


Ejercicio Numpy-10
Genera un array de 3x3 con valores aleatorios enteros entre 1 y 9. Calcula sus autovalores y autovectores, y verifica que multiplicar la matriz por un autovector da el autovalor multiplicado por el autovector.

In [37]:
A = np.random.randint(1, 10, size=(3, 3))
autovalores, autovectores = np.linalg.eig(A)
print("Matriz A:")
print(A)
print("\nAutovalores:", autovalores)
print("\nAutovectores (columnas):")
print(autovectores)

Matriz A:
[[3 1 7]
 [1 7 6]
 [7 7 8]]

Autovalores: [16.67643551 -3.01385289  4.33741738]

Autovectores (columnas):
[[-0.42138947 -0.69681013  0.62701708]
 [-0.50896233 -0.316168   -0.7454156 ]
 [-0.75059194  0.64381165  0.22628559]]


In [42]:
tolerancia = 1e-5  # Para manejar errores de precisión numérica
for i in range(len(autovalores)):
    λ = autovalores[i]
    v = autovectores[:, i]  # Tomar la columna i como autovector


# Calcular A·v y λ·v
    Av = A @ v
    λv = λ * v

print(f"\nVerificación para autovalor {i+1} (λ = {λ:.4f}):")
print(f"A·v:\t{Av}")
print(f"λ·v:\t{λv}")

if np.allclose(Av, λv, atol=tolerancia):
        print("A·v ≈ λ·v La propiedad cumple")
else:
        print("La propiedad no se cumple")


Verificación para autovalor 3 (λ = 4.3374):
A·v:	[ 2.71963476 -3.23317858  0.98149506]
λ·v:	[ 2.71963476 -3.23317858  0.98149506]
A·v ≈ λ·v La propiedad cumple
