In [1]:
import numpy as np

Ejercicio Numpy-01
Crea un array 3x4 con valores enteros aleatorios entre 10 y 50. Luego, calcula la suma, la media, y el valor máximo de todo el array.

In [6]:

# Crear un array 3x4 con valores enteros aleatorios entre 10 y 50

array_aleatorio = np.random.randint(10, 51, size=(3, 4))

# Calcular las estadísticas solicitadas

suma_total = np.sum(array_aleatorio)
media_total = np.mean(array_aleatorio)
maximo_total = np.max(array_aleatorio)

# Mostrar resultados
print("Array generado:")
print(array_aleatorio)
print("\nResultados:")
print(f"Suma total: {suma_total}")
print(f"Media total: {media_total:.2f}")  # Formateado a 2 decimales
print(f"Valor máximo: {maximo_total}")

Array generado:
[[26 33 35 13]
 [10 50 46 48]
 [27 12 23 12]]

Resultados:
Suma total: 335
Media total: 27.92
Valor máximo: 50


Ejercicio Numpy-02
Crea una matriz identidad 5x5 y cambia la diagonal principal a un valor de 7.

In [ ]:
# Crear una matriz identidad 5x5
# np.eye(N) crea una matriz identidad de NxN (en este caso 5x5)
# Por defecto, tiene 1s en la diagonal principal y 0s en las demás posiciones

matriz_identidad = np.eye(5)

# Modificar la diagonal principal a 7
# np.fill_diagonal() es una función específica para modificar los valores de la diagonal principal
# Recibe como parámetros la matriz y el valor a asignar (7 en este caso)

np.fill_diagonal(matriz_identidad, 7)

print("Matriz resultante:")
print(matriz_identidad)

Matriz resultante:
[[7. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0.]
 [0. 0. 7. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 7.]]


In [5]:
# Utilizando indices.

# Crear matriz identidad

matriz = np.eye(5)

# Modificar diagonal usando índices

filas, columnas = matriz.shape
for i in range(filas):
    matriz[i, i] = 7

matriz

array([[7., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0.],
       [0., 0., 7., 0., 0.],
       [0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 7.]])

Ejercicio Numpy-03
Dado el array a = np.arange(20), crea un nuevo array con los valores pares mayores que 5 usando boolean masking.

In [ ]:
a = np.arange(20)
mask = (a % 2 == 0) & (a > 5)
resultado = a[mask]

print("Array original:", a)
print("Array filtrado:", resultado)

# a % 2 == 0: Identifica valores pares (divisibles entre 2)
# a > 5: Identifica valores mayores que 5
# &: Combina ambas condiciones (AND lógico)

Array original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Array filtrado: [ 6  8 10 12 14 16 18]


Ejercicio Numpy-04
Dado el array bidimensional siguiente:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Reemplaza todas las entradas de la segunda fila por 0 y luego aplana el array a una dimensión.

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = a.copy()
b[1] = 0
print(b)
b_plano = b.flatten()
b_plano


[[1 2 3]
 [0 0 0]
 [7 8 9]]


array([1, 2, 3, 0, 0, 0, 7, 8, 9])

Ejercicio Numpy-05
Crea dos arrays 1D a y b con valores [1, 2, 3] y [4, 5, 6]. Realiza el producto cruzado, producto escalar y producto externo.

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
cruzado = np.cross(a, b)
escalar = np.dot(a, b)
externo = np.outer(a, b)
print("Array a:", a)
print("Array b:", b)
print("\nProducto cruzado (a x b):", cruzado)
print("Producto escalar (a · b):", escalar)
print("\nProducto externo (a x b):")
print(externo)

Array a: [1 2 3]
Array b: [4 5 6]

Producto cruzado (a x b): [-3  6 -3]
Producto escalar (a · b): 32

Producto externo (a x b):
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


Ejercicio Numpy-06
Crea un array de 10 elementos que vayan de 0 a 100 de forma equiespaciada, redondea cada elemento a su entero más cercano, y luego limita sus valores para que estén entre 20 y 80.

In [ ]:
array = np.linspace(0, 100, 10)
print(array)
array_redondeado = np.round(array).astype(int)
print(array_redondeado)
array_limitado = np.clip(array_redondeado, 20, 80)
print(array_limitado)

# resultado = np.clip(np.round(np.linspace(0, 100, 10)).astype(int), 20, 80)
# print(resultado)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[  0  11  22  33  44  56  67  78  89 100]
[20 20 22 33 44 56 67 78 80 80]


Ejercicio Numpy-07
Crea una matriz aleatoria 4x4 con valores entre 0 y 1. Multiplica la matriz por sí misma (producto matricial) y calcula la traza del resultado.

In [31]:
traza = np.trace(np.dot(matriz := np.random.rand(4,4), matriz))
traza              


np.float64(5.32163598328548)

Ejercicio Numpy-08
Dado el array a = np.array([10, 20, 30, 40, 50]), crea una máscara booleana para seleccionar los elementos que no estén en la lista [20, 40].

In [33]:
a = np.array([10, 20, 30, 40, 50])
mask = ~np.isin(a, [20, 40]) 
# El operador ~ (NOT) invierte la máscara
resultado = a[mask]
resultado

array([10, 30, 50])

Ejercicio Numpy-09
Crea un array 2x3 lleno de 5s, otro 3x2 lleno de 10s, y concaténalos verticalmente tras hacer el reshape adecuado para que la concatenación sea posible.

In [35]:
arr_5s = np.full((2, 3), 5)
arr_10s = np.full((3, 2), 10)

# Mismo numero de columnas
arr_5s_reshaped = arr_5s.reshape(6, 1)
arr_10s_reshaped = arr_10s.reshape(6, 1)

resultado = np.concatenate((arr_5s_reshaped, arr_10s_reshaped), axis=0)

# print(arr_5s_reshaped)
# print(arr_10s_reshaped)
# print(resultado)

print("Array de 5s (2x3):")
print(arr_5s)
print("\nArray de 10s (3x2):")
print(arr_10s)
print("\nArray de 5s redimensionado (6x1):")
print(arr_5s_reshaped)
print("\nArray de 10s redimensionado (6x1):")
print(arr_10s_reshaped)
print("\nConcatenación vertical (12x1):")
print(resultado)


Array de 5s (2x3):
[[5 5 5]
 [5 5 5]]

Array de 10s (3x2):
[[10 10]
 [10 10]
 [10 10]]

Array de 5s redimensionado (6x1):
[[5]
 [5]
 [5]
 [5]
 [5]
 [5]]

Array de 10s redimensionado (6x1):
[[10]
 [10]
 [10]
 [10]
 [10]
 [10]]

Concatenación vertical (12x1):
[[ 5]
 [ 5]
 [ 5]
 [ 5]
 [ 5]
 [ 5]
 [10]
 [10]
 [10]
 [10]
 [10]
 [10]]


In [36]:
arr_5s = np.full((2, 3), 5).reshape(-1, 1)  # -1 significa "calcula automáticamente"
arr_10s = np.full((3, 2), 10).reshape(-1, 1)

resultado = np.vstack((arr_5s, arr_10s))

print(resultado)

[[ 5]
 [ 5]
 [ 5]
 [ 5]
 [ 5]
 [ 5]
 [10]
 [10]
 [10]
 [10]
 [10]
 [10]]


Ejercicio Numpy-10
Genera un array de 3x3 con valores aleatorios enteros entre 1 y 9. Calcula sus autovalores y autovectores, y verifica que multiplicar la matriz por un autovector da el autovalor multiplicado por el autovector.

In [37]:
A = np.random.randint(1, 10, size=(3, 3))
autovalores, autovectores = np.linalg.eig(A)
print("Matriz A:")
print(A)
print("\nAutovalores:", autovalores)
print("\nAutovectores (columnas):")
print(autovectores)

Matriz A:
[[3 1 7]
 [1 7 6]
 [7 7 8]]

Autovalores: [16.67643551 -3.01385289  4.33741738]

Autovectores (columnas):
[[-0.42138947 -0.69681013  0.62701708]
 [-0.50896233 -0.316168   -0.7454156 ]
 [-0.75059194  0.64381165  0.22628559]]


In [42]:
tolerancia = 1e-5  # Para manejar errores de precisión numérica
for i in range(len(autovalores)):
    λ = autovalores[i]
    v = autovectores[:, i]  # Tomar la columna i como autovector


# Calcular A·v y λ·v
    Av = A @ v
    λv = λ * v

print(f"\nVerificación para autovalor {i+1} (λ = {λ:.4f}):")
print(f"A·v:\t{Av}")
print(f"λ·v:\t{λv}")

if np.allclose(Av, λv, atol=tolerancia):
        print("A·v ≈ λ·v La propiedad cumple")
else:
        print("La propiedad no se cumple")


Verificación para autovalor 3 (λ = 4.3374):
A·v:	[ 2.71963476 -3.23317858  0.98149506]
λ·v:	[ 2.71963476 -3.23317858  0.98149506]
A·v ≈ λ·v La propiedad cumple


Ejercicio Numpy-11Crea un sistema de ecuaciones 3x3 y resuélvelo usando np.linalg.solve. El sistema es:2x + 3y -z = 5, x + 7y + 2z = 3, 4x -5y + 6z = 10

In [2]:
# Paso 1: Definir matriz de coeficientes (A) y vector de resultados (B)
A = np.array([
    [2, 3, -1],  # Coeficientes primera ecuación
    [1, 7, 2],   # Coeficientes segunda ecuación
    [4, -5, 6]   # Coeficientes tercera ecuación
])

B = np.array([5, 3, 10])  # Términos independientes

# Paso 2: Resolver el sistema
solucion = np.linalg.solve(A, B)

# Paso 3: Mostrar resultados
x, y, z = solucion
print(f"Solución del sistema:")
print(f"x = {x:.4f}")
print(f"y = {y:.4f}")
print(f"z = {z:.4f}")

# (Opcional) Verificar solución
verificacion = np.allclose(np.dot(A, solucion), B)
print(f"\n¿La solución es correcta? {'Sí' if verificacion else 'No'}")

Solución del sistema:
x = 2.4545
y = 0.0559
z = 0.0769

¿La solución es correcta? Sí


Ejercicio Numpy-12Genera un array de 50 números aleatorios del 0 al 100. Separa el array en 5 partes iguales y calcula la media de cada una.

In [3]:
# Generar array de 50 números aleatorios entre 0 y 100
random_array = np.random.randint(0, 101, 50)

# Dividir en 5 partes iguales
partes = np.array_split(random_array, 5)

# Calcular media de cada parte
medias = [np.mean(parte) for parte in partes]

# Mostrar resultados
print("Array completo:")
print(random_array)

print("\nPartes divididas:")
for i, parte in enumerate(partes, 1):
    print(f"Parte {i}: {parte}")

print("\nMedias de cada parte:")
for i, media in enumerate(medias, 1):
    print(f"Media parte {i}: {media:.2f}")

Array completo:
[86  2 85  0 33 85 50 22 89 50  7 51 19 79 69 21 18 99 21 51 22 14 78 78
  6 81  8  5 25 33 73 47 99 11  3 79 21 53 86 93 31 77 40 24 66 94 21 93
 26 25]

Partes divididas:
Parte 1: [86  2 85  0 33 85 50 22 89 50]
Parte 2: [ 7 51 19 79 69 21 18 99 21 51]
Parte 3: [22 14 78 78  6 81  8  5 25 33]
Parte 4: [73 47 99 11  3 79 21 53 86 93]
Parte 5: [31 77 40 24 66 94 21 93 26 25]

Medias de cada parte:
Media parte 1: 50.20
Media parte 2: 43.50
Media parte 3: 35.00
Media parte 4: 56.50
Media parte 5: 49.70


Ejercicio Numpy-13Dado un array 2D a = np.arange(1, 17).reshape(4,4), intercambia filas y columnas (transpuesta), luego ordena cada fila y devuelve los índices de ordenación

In [4]:
# Crear el array 2D
a = np.arange(1, 17).reshape(4, 4)
print("Array original:")
print(a)

# Paso 1: Intercambiar filas y columnas (transpuesta)
transpuesta = a.T
print("\nTranspuesta:")
print(transpuesta)

# Paso 2: Ordenar cada fila de la transpuesta
array_ordenado = np.sort(transpuesta, axis=1)
print("\nTranspuesta con filas ordenadas:")
print(array_ordenado)

# Paso 3: Obtener los índices de ordenación
indices_orden = np.argsort(transpuesta, axis=1)
print("\nÍndices de ordenación por fila:")
print(indices_orden)

Array original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpuesta:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Transpuesta con filas ordenadas:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Índices de ordenación por fila:
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


Ejercicio Numpy-14Crea un array 1D con valores del 1 al 15. Itera sobre él con np.nditery crea otro array que contenga el cuadrado de cada elemento.

In [5]:

# Crear array 1D con valores del 1 al 15
arr = np.arange(1, 16)
print("Array original:")
print(arr)

# Crear array vacío para almacenar los cuadrados
squares = np.empty(arr.shape, dtype=arr.dtype)

# Iterar usando np.nditer y calcular cuadrados
with np.nditer(arr, flags=['c_index'], op_flags=['readonly']) as it:
    for x in it:
        squares[it.index] = x ** 2

print("\nArray de cuadrados:")
print(squares)

Array original:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Array de cuadrados:
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]


Ejercicio Numpy-15. Crea una matriz 4x4 con valores aleatorios enteros entre 0 y 9. Usa np.wherepara cambiar todos los valores menores que 5 por -1, y los demás déjalos iguales

In [6]:
# Crear matriz 4x4 con enteros aleatorios entre 0 y 9
matriz = np.random.randint(0, 10, size=(4, 4))
print("Matriz original:")
print(matriz)

# Cambiar valores menores que 5 por -1, mantener los demás
matriz_modificada = np.where(matriz < 5, -1, matriz)

print("\nMatriz modificada:")
print(matriz_modificada)

Matriz original:
[[2 4 0 8]
 [9 2 1 7]
 [4 0 6 0]
 [7 0 5 5]]

Matriz modificada:
[[-1 -1 -1  8]
 [ 9 -1 -1  7]
 [-1 -1  6 -1]
 [ 7 -1  5  5]]


Ejercicio Numpy-16. Eres un ingeniero que debe resolver un sistema lineal de 4 ecuaciones con 4 incógnitas para modelar el equilibrio de fuerzas en una estructura. El sistema es:3x+y−z+2w=52 x−2y+4z−w=−2 −x+21y−z+w=0 x+y+z+w=3 Además, calcula la inversa de la matriz de coeficientes y comprueba que la multiplicación entre matriz e inversa da la matriz identidad.

In [7]:

# Matriz de coeficientes (4x4)
A = np.array([
    [ 3,  1, -1,  2],  # Ecuación 1
    [ 1, -2,  4, -1],  # Ecuación 2
    [-1, 21, -1,  1],  # Ecuación 3
    [ 1,  1,  1,  1]   # Ecuación 4
])

# Vector de términos independientes
B = np.array([52, -2, 0, 3])

# 1. Resolver el sistema
solucion = np.linalg.solve(A, B)
x, y, z, w = solucion

# 2. Verificar la solución
verificacion = np.allclose(A @ solucion, B)

# 3. Calcular la inversa
try:
    A_inv = np.linalg.inv(A)
    # Comprobar inversa (A · A_inv ≈ Identidad)
    identidad_aproximada = A @ A_inv
    es_identidad = np.allclose(identidad_aproximada, np.eye(4))
except np.linalg.LinAlgError:
    A_inv = None
    es_identidad = False

# 4. Calcular número de condición
condicion = np.linalg.cond(A)

# Resultados
print("Solución del sistema:")
print(f"x = {x:.6f}\ny = {y:.6f}\nz = {z:.6f}\nw = {w:.6f}")
print(f"\n¿Solución verificada? {'Sí' if verificacion else 'No'}")

print("\nNúmero de condición de la matriz:", f"{condicion:.4e}")

if A_inv is not None:
    print("\nInversa de A (primeras 2 decimales):")
    print(np.round(A_inv, 2))
    
    print("\nComprobación inversa (A * A_inv):")
    print(np.round(identidad_aproximada, 2))
    print(f"¿Es la matriz identidad? {'Sí' if es_identidad else 'No'}")
else:
    print("\nLa matriz es singular, no tiene inversa")

Solución del sistema:
x = 22.067961
y = 1.218447
z = -8.383495
w = -11.902913

¿Solución verificada? Sí

Número de condición de la matriz: 3.6303e+01

Inversa de A (primeras 2 decimales):
[[ 0.48  0.3   0.04 -0.69]
 [ 0.03  0.04  0.05 -0.07]
 [-0.18  0.09 -0.    0.46]
 [-0.32 -0.43 -0.09  1.3 ]]

Comprobación inversa (A * A_inv):
[[ 1. -0. -0.  0.]
 [ 0.  1. -0.  0.]
 [-0.  0.  1.  0.]
 [ 0. -0.  0.  1.]]
¿Es la matriz identidad? Sí


Ejercicio Numpy-17. Como científico de datos, generas un conjunto de vectores 3D aleatorios para analizar su orientación. Genera 10 vectores 3D con valores aleatorios entre -10 y 10. Para cada vector, calcula su módulo (norma) y normalízalo (vector unitario). 
Después, calcula la matriz de producto externo para cada vector normalizado y almacena todas esas matrices en un array 3D de dimensiones (10, 3, 3)

In [8]:
# Paso 1: Generar 10 vectores 3D aleatorios entre -10 y 10
vectores = np.random.uniform(-10, 10, size=(10, 3))
print("Vectores originales:")
print(vectores)

# Paso 2: Calcular el módulo (norma) de cada vector
normas = np.linalg.norm(vectores, axis=1, keepdims=True)
print("\nNormas de los vectores:")
print(normas.flatten())

# Paso 3: Normalizar los vectores (convertir en unitarios)
# Agregar un pequeño epsilon para evitar división por cero
epsilon = 1e-10
vectores_unitarios = vectores / (normas + epsilon)
print("\nVectores normalizados (unitarios):")
print(vectores_unitarios)

# Paso 4: Calcular las matrices de producto externo
# Crear array 3D para almacenar las matrices (10, 3, 3)
matrices_producto_externo = np.zeros((10, 3, 3))

for i in range(10):
    u = vectores_unitarios[i]
    # Calcular producto externo: u ⊗ u = u · u^T
    matrices_producto_externo[i] = np.outer(u, u)
    
    # Alternativa vectorizada:
    # matrices_producto_externo[i] = u[:, np.newaxis] * u[np.newaxis, :]

print("\nPrimera matriz de producto externo:")
print(matrices_producto_externo[0])

Vectores originales:
[[ 4.9090562  -7.00694295  0.49981593]
 [-8.01009599  3.30737778  0.10950039]
 [ 7.37555926 -9.79460379  8.73837841]
 [-0.91704617  0.11105953  7.76663111]
 [ 2.95607367 -7.71393451 -4.82767219]
 [-0.67318063  9.86332127  0.92078309]
 [-3.28091608 -7.15921128 -7.7475441 ]
 [ 3.69561302 -6.31291465 -4.56451977]
 [-8.56707837 -9.11554883  8.7412615 ]
 [-1.08264249 -7.66970783 -4.52849298]]

Normas de los vectores:
[ 8.57005824  8.66673963 15.05630748  7.82137243  9.56815426  9.92905435
 11.04731443  8.62237135 15.26098669  8.97238996]

Vectores normalizados (unitarios):
[[ 0.5728148  -0.81760739  0.05832118]
 [-0.92423406  0.3816173   0.01263455]
 [ 0.48986508 -0.6505316   0.58037991]
 [-0.11724875  0.01419949  0.99300106]
 [ 0.30894921 -0.80620925 -0.50455627]
 [-0.06779907  0.99337972  0.09273623]
 [-0.29698766 -0.64804992 -0.70130566]
 [ 0.4286075  -0.73215527 -0.52938102]
 [-0.5613712  -0.59731058  0.57278482]
 [-0.12066378 -0.85481214 -0.50471424]]

Primera matr

Ejercicio Numpy-18. Un físico está estudiando un sistema cuántico con una matriz Hamiltoniana hermítica 4x4 generada aleatoriamente. Genera esta matriz hermítica (simétrica y con valores complejos conjugados) con números complejos aleatorios. Calcula los autovalores y autovectores, y verifica que la matriz es diagonalizable, es decir, que H @ V = V @ D, donde Des la matriz diagonal de autovalores.

In [9]:
# Paso 1: Generar matriz hermítica aleatoria 4x4
def generar_matriz_hermitica(n=4):
    # Crear matriz compleja aleatoria
    parte_real = np.random.uniform(-10, 10, (n, n))
    parte_imag = np.random.uniform(-10, 10, (n, n))
    A = parte_real + 1j * parte_imag
    
    # Hacerla hermítica: H = (A + A†)/2
    H = (A + A.conj().T) / 2
    return H

# Generar la matriz Hamiltoniana
H = generar_matriz_hermitica()
print("Matriz Hamiltoniana H:")
print(np.round(H, 2))

# Paso 2: Calcular autovalores y autovectores
autovalores, autovectores = np.linalg.eigh(H)
V = autovectores  # Matriz de autovectores (columnas)

# Construir matriz diagonal D
D = np.diag(autovalores)

# Paso 3: Verificar diagonalización
# Calcular H @ V y V @ D
HV = H @ V
VD = V @ D

# Comprobar igualdad con tolerancia numérica
es_diagonalizable = np.allclose(HV, VD, atol=1e-10)

# Paso 4: Verificar propiedades de hermiticidad
es_hermitica = np.allclose(H, H.conj().T, atol=1e-10)

# Resultados
print("\nAutovalores:")
print(np.round(autovalores, 4))

print("\n¿La matriz es hermítica?", "Sí" if es_hermitica else "No")
print("¿Es diagonalizable?", "Sí" if es_diagonalizable else "No")

# Verificación adicional: error relativo
error_relativo = np.linalg.norm(HV - VD) / np.linalg.norm(HV)
print(f"\nError relativo: {error_relativo:.4e}")

Matriz Hamiltoniana H:
[[-2.21+0.j    0.77+2.44j -3.93-2.54j  2.82+2.04j]
 [ 0.77-2.44j  0.75+0.j    1.11+0.36j  0.12+1.04j]
 [-3.93+2.54j  1.11-0.36j -3.25+0.j    4.13-0.35j]
 [ 2.82-2.04j  0.12-1.04j  4.13+0.35j  8.29+0.j  ]]

Autovalores:
[-9.6243 -0.0297  3.1203 10.1196]

¿La matriz es hermítica? Sí
¿Es diagonalizable? Sí

Error relativo: 4.6589e-16


Ejercicio Numpy-19.
Un investigador analiza la evolución temporal de un sistema descrito por una matriz de transición 5x5. Genera una matriz estocástica (cada fila suma 1 y todos los valores son positivos) y calcula su estado estable como el autovector asociado al autovalor 1, normalizado para que la suma de sus componentes sea 1.

In [10]:
# Paso 1: Definición de la matriz estocástica 5x5
P = np.array([
    [0.20, 0.30, 0.10, 0.25, 0.15],
    [0.10, 0.40, 0.20, 0.15, 0.15],
    [0.30, 0.20, 0.30, 0.10, 0.10],
    [0.25, 0.15, 0.15, 0.30, 0.15],
    [0.15, 0.10, 0.25, 0.20, 0.30]
])

# Paso 2: Definición del estado estable
def calcular_estado_estable(P, iteraciones=1000):
    # Paso 3: Vector inicial
    pi = np.ones(P.shape[0]) / P.shape[0]  # Vector inicial uniforme
    for _ in range(iteraciones):
        pi = np.dot(pi, P)  # Iteración de la potencia
    return pi / np.sum(pi)  # Normalización

# Paso 4: Calcular el estado estable
estado_estable = calcular_estado_estable(P)

# Paso 5: Resultado
print("El vector de estado estable es:", estado_estable)


El vector de estado estable es: [0.19732143 0.24170918 0.19846939 0.19770408 0.16479592]


Ejercicio Numpy-20.
Un matemático quiere comprobar la propiedad de ortogonalidad de un conjunto de vectores generados mediante la función np.eyecon pequeñas perturbaciones gaussianas añadidas. Crea una matriz 6x6 identidad y suma a cada elemento un ruido normal con media 0 y desviación 0.01. Calcula la matriz producto M=ATA. Comprueba qué tan cerca está Mde la matriz identidad calculando la norma de la diferencia y muestra el resultado.

In [11]:
import numpy as np

# Parámetros
n = 6  # Tamaño de la matriz
desviacion_estandar = 0.01  # Desviación estándar del ruido gaussiano

# Paso 1: Crear la matriz identidad
A = np.eye(n)

# Paso 2: Añadir ruido gaussiano a cada elemento
ruido = np.random.normal(0, desviacion_estandar, size=(n, n))
A = A + ruido

# Paso 3: Calcular la matriz producto M = A.T @ A
M = A.T @ A

# Paso 4: Calcular la diferencia entre M y la matriz identidad
identidad = np.eye(n)
diferencia = M - identidad

# Paso 5: Calcular la norma de la diferencia (Frobenius)
norma_diferencia = np.linalg.norm(diferencia)

# Paso 6: Mostrar el resultado
print("Matriz A:\n", A)
print("\nMatriz M = A.T @ A:\n", M)
print("\nNorma de la diferencia entre M y la identidad:", norma_diferencia)


Matriz A:
 [[ 1.00700970e+00 -1.22984068e-02  2.90603249e-03 -1.79267280e-03
  -3.41188386e-03  5.80067124e-03]
 [ 1.12713510e-02  9.96663701e-01 -2.20372431e-02  1.45200608e-02
   7.66401315e-03 -1.20307299e-02]
 [ 1.21162093e-02 -1.21644124e-03  1.01585253e+00  1.34189298e-04
  -5.82276860e-03  4.92699986e-03]
 [ 4.29937608e-03  3.24512073e-03 -6.85033323e-04  9.98267672e-01
  -1.02434419e-02  6.50724969e-03]
 [-1.02707137e-02  7.04816737e-03  2.87823959e-02 -2.61824449e-03
   1.01293261e+00 -1.03731487e-02]
 [ 1.60787691e-03  2.38032255e-03 -1.75048686e-02 -5.99937771e-03
  -1.14568534e-04  1.00007484e+00]]

Matriz M = A.T @ A:
 [[ 1.01446894e+00 -1.22021767e-03  1.46595887e-02  2.66922081e-03
  -1.38677317e-02  7.50794016e-03]
 [-1.22021767e-03  9.93557138e-01 -2.30762119e-02  1.77002661e-02
   1.47932921e-02 -9.73941840e-03]
 [ 1.46595887e-02 -2.30762119e-02  1.03358576e+00 -8.43062788e-04
   2.30697670e-02 -1.25221140e-02]
 [ 2.66922081e-03  1.77002661e-02 -8.43062788e-04  9.9679