# NUMPY ( Numerical Python)

Biblioteca especializada en cálculo numérico (multidimensional)

In [3]:
import numpy as np

El núcleo de Numpy es el objeto ndarray (N-array dimensional)

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
type(a)

numpy.ndarray

### 1. Atributos importantes de Numpy 

.shape --> forma o elementos

.ndim --> numero de dimensiones

.size --> numero total de elementos

.dtype --> tipo de datos

In [5]:
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

[1 2 3]
(3,)
1
3
int64


### 2. Creacion de arrays

np.array( << lista >> , dtype = << tipo_dato >>) --> a partir de una lista

<ul><li>np.array(<< lista >>, dtype=complex) --> array imaginario</li></ul>

np.zeros( (x, y) )  --> array de ceros (x: numero de arrays | y : numero de elementos en cada array)

np.ones( (x, y) )  --> array de unos (x: numero de arrays | y : numero de elementos en cada array)

np.full( (x, y) , valor )  --> array de un valor determinado (x: numero de arrays | y : numero de elementos en cada array)

np.eye(<< tamaño_matriz >>)  --> matriz identidad

np.arange( inicio , final , incremento)  --> array desde un valor inicial hasta un final(no incluido) con una tasa de variacion

np.linspace( inicio , final , numer_elementos)  --> array desde un valor inicial hasta un final(incluido) con numero_elementos equiespacioados

np.random.rand( x , y ) / np.random.random( x , y )  --> valores aleatorios del 0 al 1 (x: numero de arrays | y : numero de elementos en cada array)

np.random.randint( << inicial >> , << final >>  , << numero >>)  --> numero valores aleatorios comprendisos entre un valor inicial y final


In [6]:
np.random.randint(1,10,5)

array([6, 7, 5, 6, 7], dtype=int32)

### 3. Acceder a elementos de un array

In [7]:
a = np.array([[1,2,3] , [4,5,6]])
m,n = 1,0  # fila , columna
 
a[m,n] # same a[m][n] 

np.int64(4)

### 4. Operaciones matemáticas Elemento a elemento
a+b

a-b

a*b

a/b

np.sqrt(a)

np.exp(a)

np.log(a)

np.sin(a)

np.cos(a)

a.sum()

a.mean()

a.std()

a.min()

a.max()

a.argmin()

a.argmax()

In [8]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [9]:
print(f'a = {a}')
print(f'b = {b}')
print(f'a+b = {a+b}')

a = [[1 2 3]
 [4 5 6]]
b = [4 5 6]
a+b = [[ 5  7  9]
 [ 8 10 12]]


### 5. Indexacion && Slicing

a[0] , a[-1]

a[1:2]

a[::2]

a[1:] = 0

In [10]:
A = np.array( [ [1,2,3] , [4,5,6] ] )
A

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
A[0,1]

np.int64(2)

In [12]:
A[:,1]

array([2, 5])

In [13]:
A[1, :]

array([4, 5, 6])

### 6. Filtrado && Bolean Masking

In [14]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [15]:
a>3

array([False, False, False,  True,  True])

In [16]:
mascara = a>3

a[mascara]

array([4, 5])

In [17]:
a[a % 2 == 0]

array([2, 4])

### 7. Broadcasting

In [18]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [19]:
b = 2
b

2

In [20]:
a+b

array([3, 4, 5])

### 8. Manipulacion de arrays

.reshape( <<filas>> , <<columnas>>) -> parte en una matriz de n filas y n columnas 

In [21]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [22]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

.flatten() --> de multidimensional a unidimensional

In [23]:
a = np.array([[1, 2, 3],
       [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

.concatenate([array1 ,  array2]) --> concatena array

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


In [26]:
c = np.concatenate([a, b])
c

array([1, 2, 3, 4, 5, 6])

.vstack ([array1 ,  array2]) --> apila verticalmente los array

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [28]:
c = np.vstack([a, b])
c

array([[1, 2, 3],
       [4, 5, 6]])

.hstack ([array1 ,  array2]) --> apila horizontalmente los array

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [30]:
c = np.hstack([a, b])
c

array([1, 2, 3, 4, 5, 6])

.split (array , numero_iguales) --> divide un array en n partes iguales

In [31]:
a = np.array([1, 2, 3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [32]:
np.split(a , 2)

[array([1, 2, 3]), array([4, 5, 6])]

.transpose (matriz) --> invierte los ejes

In [33]:
a = np.array([[1, 2, 3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

### 9. Copia de elementos

In [35]:
a = np.array([[1, 2, 3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
b = a.copy()

### 10. Iteracion

In [37]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [38]:
for fila in a:
    print(fila)

[1 2]
[3 4]


In [39]:
for x in np.nditer(a):
    print(x)

1
2
3
4


In [40]:
for i , x in np.ndenumerate(a):
    print(i, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


### 11. Metodos Utiles

np.unique(array/matrix) --> valores unicos

In [41]:
a = np.array([1, 2, 2, 3, 3, 3])
np.unique(a)

array([1, 2, 3])

np.sort(array) --> ordenacion de valores

In [42]:
a = np.array([3, 1, 4, 2])
np.sort(a)

array([1, 2, 3, 4])

np.argsort(array) --> devuelve los indices del array ordenado

In [43]:
a = np.array([3, 1, 4, 2])
np.argsort(a)

array([1, 3, 0, 2])

np.where( condicion , valor_si_True , valor_si_falso)

In [44]:
a = np.array([1, 2, 3, 4])

np.where(a>2, 1 , 0)

array([0, 0, 1, 1])

np.any(condicion) --> si algún elemento en el array/matriz cumple la condicion me devuelve True

In [45]:
a = np.array([1, 2, 3, 4])

np.any(a>100)

np.False_

np.isin(matirz , lista) --> devuelve array de boleanos si el elemento de la matriz está en la lista proprorcionada

In [46]:
a = np.array([1, 2, 3, 4])

np.isin(a , [1,4,1000])

array([ True, False, False,  True])

np.clip(matriz , min_val , max_val ) --> limitar los valores del array a un rango

In [47]:
a = np.array([-5, 0, 5, 10, 15])

np.clip(a, 0, 10)

array([ 0,  0,  5, 10, 10])

### 12. Algebra Lineal 

dot(a,b) / a@b / np.inner(a,b) --> producto escalar

In [48]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

<small> El producto escalar es:  
    a⋅b=1×4+2×5+3×6=32 </small>

In [49]:
np.dot(a, b)

np.int64(32)

In [51]:
a @ b

np.int64(32)

In [52]:
np.inner(a, b)


np.int64(32)

np.cross(a,b) --> producto vectorial o producto cruzado

<small>

Sean:

$$
\vec{a} = [a_1, a_2, a_3], \quad \vec{b} = [b_1, b_2, b_3]
$$

El producto vectorial se define como:

$$
\vec{a} \times \vec{b} =
\begin{bmatrix}
a_2 b_3 - a_3 b_2 \\
a_3 b_1 - a_1 b_3 \\
a_1 b_2 - a_2 b_1
\end{bmatrix}
$$

---

Ejemplo, sean:

$$
\vec{a} = [1, 0, 0], \quad \vec{b} = [0, 1, 0]
$$

Entonces:

$$
\vec{a} \times \vec{b} =
\begin{bmatrix}
0 \cdot 0 - 0 \cdot 1 \\
0 \cdot 0 - 1 \cdot 0 \\
1 \cdot 1 - 0 \cdot 0
\end{bmatrix}
=
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix}
$$
</small>

<small>El producto cruzado de dos vectores 3D, a y b, da como resultado un nuevo vector perpendicular a ambos</small>

In [53]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

c = np.cross(a, b)
print(c)  # el vector [0, 0, 1], que es perpendicular a a y b.

[0 0 1]


np.outer(a,b) --> producto combinado

<small>Dado dos vectores 1D, a y b, calcula todas las combinaciones posibles multiplicando cada elemento de a por cada elemento de b: 

$$
C_{ij} = a_i \cdot b_j
$$

</small>

In [54]:
a = np.array([1, 2])
b = np.array([3, 4, 5])
np.outer(a, b)

array([[ 3,  4,  5],
       [ 6,  8, 10]])

np.linalg.norm(<< vector >>) --> modulo de un vector

In [56]:
v = np.array([3, 4])

np.linalg.norm(v)

np.float64(5.0)

np.matmul(A,B) --> Producto matricial

<small>Realiza la multiplicación de matrices siguiendo la regla algebraica estándar:

$$
C_{ij} = \sum_{k=1}^{n} A_{ik} \cdot B_{kj}
$$


<small>

$$
A =
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{bmatrix},
\quad
B =
\begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22}
\end{bmatrix}
$$

$$
A \cdot B =
\begin{bmatrix}
a_{11}b_{11} + a_{12}b_{21} & a_{11}b_{12} + a_{12}b_{22} \\
a_{21}b_{11} + a_{22}b_{21} & a_{21}b_{12} + a_{22}b_{22}
\end{bmatrix}
$$
</small>

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.matmul(A, B)


<< matriz >>.T --> transpuesta de una matriz

In [58]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matriz A:")
print(A)

print("\nTranspuesta de A (A.T):")
print(A.T)

Matriz A:
[[1 2 3]
 [4 5 6]]

Transpuesta de A (A.T):
[[1 4]
 [2 5]
 [3 6]]


<< matriz >>.trace --> traza de una matriz (suma de diagonal principal)

In [59]:
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
traza = matriz.trace()

print("La matriz es:")
print(matriz)
print("La traza de la matriz es:", traza)

La matriz es:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
La traza de la matriz es: 15


np.linalg.inv(A) --> Inversa de la matriz

In [60]:
A = np.array([
    [1, 2],
    [3, 4]
])
A_inv = np.linalg.inv(A)

print("Matriz A:")
print(A)
print("Inversa de A:")
print(A_inv)

Matriz A:
[[1 2]
 [3 4]]
Inversa de A:
[[-2.   1. ]
 [ 1.5 -0.5]]


np.linalg.det(A) --> Determinante de la matriz

In [61]:
A = np.array([
    [1, 2],
    [3, 4]
])

determinante = np.linalg.det(A)

print("Matriz A:")
print(A)
print("Determinante de A:", determinante)

Matriz A:
[[1 2]
 [3 4]]
Determinante de A: -2.0000000000000004


np.linalg.eig(A) --> Autovalores y autovectores

In [ ]:
A = np.array([
    [4, 2],
    [1, 3]
])

In [62]:
autovalores, autovectores = np.linalg.eig(A)

print("Matriz A:")
print(A)
print("Autovalores:")
print(autovalores)
print("Autovectores:")
print(autovectores)

Matriz A:
[[1 2]
 [3 4]]
Autovalores:
[-0.37228132  5.37228132]
Autovectores:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


np.linalg.eigvals(A) --> Autovalores 

In [63]:
A = np.array([
    [4, 2],
    [1, 3]
])

autovalores = np.linalg.eigvals(A)

print("Matriz A:")
print(A)
print("Autovalores:")
print(autovalores)

Matriz A:
[[4 2]
 [1 3]]
Autovalores:
[5. 2.]


np.linalg.solve(<< matriz de coeficientes >>, << matriz de soluciones >>) --> resolucion de un sistema de ecuaciones

In [64]:
# Sistema de ecuaciones:
# 2x + 3y = 8
# 5x + 4y = 13

A = np.array([
    [2, 3],
    [5, 4]
])

b = np.array([8, 13])

# Resolver el sistema
solucion = np.linalg.solve(A, b)

print("Solución del sistema:")
print("x =", solucion[0])
print("y =", solucion[1])

Solución del sistema:
x = 1.0
y = 2.0


### Guardado

save(nombre_archivo , cursor) -> guaardar

load(nombre_archivo) --> cargar

savetxt(nombre_archivo , cursor, delimiter=',') -> guaardar como texto
